description: >
  Container for charge model configuration data.


  **Note**: This field is only available if you have the High Water Mark,
  Pre-Rated Pricing, or Multi-Attribute Pricing charge models enabled. These
  charge models are available for customers with Enterprise and Nine editions by
  default. If you are a Growth customer, see [Zuora
  Editions](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/C_Zuora_Editions)
  for pricing information.
properties:
  customFieldPerUnitRate:
    description: >
      The custom field that carries the per-unit rate for each usage record. For
      example, `perUnitAmount__c`.
          
      This field is only available for the usage-based charges that use the
      Pre-Rated Per Unit Pricing charge model. The charge model is available for
      customers with Enterprise and Nine editions by default. If you are a
      Growth customer, see [Zuora
      Editions](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/C_Zuora_Editions)
      for pricing information.
    type: string
  customFieldTotalAmount:
    description: >
      The custom field that carries the total amount to charge for a usage
      record. For example, `totalAmount__c`. 
          
      This field is only available for the usage-based charges that use the
      Pre-Rated Pricing charge model. The charge model is available for
      customers with Enterprise and Nine editions by default. If you are a
      Growth customer, see [Zuora
      Editions](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/C_Zuora_Editions)
      for pricing information.
    type: string
  formula:
    description: >
      The pricing formula to calculate actual rating amount for each usage
      record.


      This field is only available for the usage-based charges that use the
      Multi-Attribute Pricing charge model. The charge model is available for
      customers with Enterprise and Nine editions by default. If you are a
      Growth customer, see [Zuora
      Editions](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/C_Zuora_Editions)
      for pricing information.
    type: string
title: chargeModelConfiguration
type: object
