description: >
  Container for Product Rate Plan fields provided by the [Zuora Connector for
  NetSuite](https://www.zuora.com/connect/app/?appId=265).
properties:
  BillingPeriod__NS:
    description: >
      Billing period associated with the corresponding item in NetSuite. Only
      available if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    enum:
      - Monthly
      - Quarterly
      - Annual
      - Semi-Annual
    type: string
  Class__NS:
    description: >
      Class associated with the corresponding item in NetSuite. Only available
      if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    maxLength: 255
    type: string
  Department__NS:
    description: >
      Department associated with the corresponding item in NetSuite. Only
      available if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    maxLength: 255
    type: string
  IncludeChildren__NS:
    description: >
      Specifies whether the corresponding item in NetSuite is visible under
      child subsidiaries. Only available if you have installed the [Zuora
      Connector for NetSuite](https://www.zuora.com/connect/app/?appId=265).
    enum:
      - 'Yes'
      - 'No'
    type: string
  IntegrationId__NS:
    description: >
      ID of the corresponding object in NetSuite. Only available if you have
      installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    maxLength: 255
    type: string
  IntegrationStatus__NS:
    description: >
      Status of the product rate plan's synchronization with NetSuite. Only
      available if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    maxLength: 255
    type: string
  ItemType__NS:
    description: >
      Type of item that is created in NetSuite for the product rate plan. Only
      available if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    enum:
      - Inventory
      - Non Inventory
      - Service
    type: string
  Location__NS:
    description: >
      Location associated with the corresponding item in NetSuite. Only
      available if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    maxLength: 255
    type: string
  MultiCurrencyPrice__NS:
    description: >
      Multi-currency price associated with the corresponding item in NetSuite.
      Only available if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    maxLength: 255
    type: string
  Price__NS:
    description: >
      Price associated with the corresponding item in NetSuite. Only available
      if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    maxLength: 255
    type: string
  Subsidiary__NS:
    description: >
      Subsidiary associated with the corresponding item in NetSuite. Only
      available if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    maxLength: 255
    type: string
  SyncDate__NS:
    description: >
      Date when the product rate plan was synchronized with NetSuite. Only
      available if you have installed the [Zuora Connector for
      NetSuite](https://www.zuora.com/connect/app/?appId=265).
    maxLength: 255
    type: string
title: productRatePlanFieldsNS
type: object
