description: |
  A workflow.
properties:
  calloutTrigger:
    description: >
      Indicates whether the callout trigger is enabled for the retrieved
      workflow.
    type: boolean
  createdAt:
    description: >
      The date and time when the workflow is created, in the `YYYY-MM-DD
      HH:MM:SS` format.
    format: datetime
    type: string
  description:
    description: |
      The description of the workflow.
    type: string
  id:
    description: |
      The unique ID of the workflow.
    type: integer
  interval:
    description: >
      The schedule of the workflow, in a CRON expression. Returns null if the
      schedued trigger is disabled.
    type: string
  name:
    description: |
      The name of the workflow.
    type: string
  ondemandTrigger:
    description: |
      Indicates whether the ondemand trigger is enabled for the workflow.
    type: boolean
  scheduledTrigger:
    description: |
      Indicates whether the scheduled trigger is enabled for the workflow.
    type: boolean
  timezone:
    description: >
      The timezone that is configured for the scheduler of the workflow. Returns
      null if the scheduled trigger is disabled.
    type: string
  type:
    description: >
      The type of the workflow. Currently the only valid value is
      'Workflow::Setup'.
    enum:
      - Workflow::Setup
      - Workflow::Instance
    type: string
  updatedAt:
    description: >
      The date and time when the workflow is updated the last time, in the
      `YYYY-MM-DD HH:MM:SS` format.
    format: datetime
    type: string
  version:
    description: |
      The version number of the workflow. 
    type: string
title: workflow
type: object
