get:
  summary: List all application parts of an invoice
  description: >
    **Note:** This operation is only available if you have [Invoice
    Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)
    enabled. The Invoice Settlement feature is generally available as of Zuora
    Billing Release 296 (March 2021). This feature includes Unapplied Payments,
    Credit and Debit Memo, and Invoice Item Settlement. If you want to enable
    Invoice Settlement, see [Invoice Settlement Enablement and Checklist
    Guide](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement/Invoice_Settlement_Migration_Checklist_and_Guide)
    for more information.


    Retrieves information about the payments or credit memos that are applied to
    a specified invoice.
  operationId: GET_InvoiceApplicationParts
  tags:
    - Invoices
  parameters:
    - $ref: ../components/parameters/GLOBAL_HEADER_Zuora_Track_Id.yaml
    - $ref: ../components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single.yaml
    - name: invoiceId
      in: path
      required: true
      description: >
        The unique ID of an invoice. For example,
        2c92c8955bd63cc1015bd7c151af02ab.
      schema:
        type: string
  responses:
    '200':
      headers:
        RateLimit-Limit:
          description: >
            The request limit quota for the time window closest to exhaustion.
            See [rate
            limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
            for more information.
          schema:
            type: string
        RateLimit-Remaining:
          description: >
            The number of requests remaining in the time window closest to quota
            exhaustion. See [rate
            limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
            for more information.
          schema:
            type: number
        RateLimit-Reset:
          description: >
            The number of seconds until the quota resets for the time window
            closest to quota exhaustion. See [rate
            limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
            for more information.
          schema:
            type: number
        Zuora-Request-Id:
          description: >
            The Zuora internal identifier of the API call. You cannot control
            the value of this header.
          schema:
            type: string
            minLength: 36
            maxLength: 36
        Zuora-Track-Id:
          description: >
            A custom identifier for tracing the API call. If you specified a
            tracing identifier in the request headers, Zuora returns the same
            tracing identifier. Otherwise, Zuora does not set this header.
          schema:
            type: string
            maxLength: 64
      description: OK
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ../components/schemas/GetInvoiceApplicationPartCollectionType.yaml
        application/json:
          examples:
            response:
              value:
                applicationParts:
                  - paymentId: null
                    creditMemoId: 4028905f60a165a50160b4f632ff023d
                    appliedAmount: 22
                    createdDate: '2018-01-02 11:42:16'
                    createdById: 402881e522cf4f9b0122cf5d82860002
                    updatedDate: '2018-01-02 11:42:16'
                    updatedById: 402881e522cf4f9b0122cf5d82860002
                  - paymentId: 4028905f60a165a50160b4f5d5cb0229
                    creditMemoId: null
                    appliedAmount: 11
                    createdDate: '2018-01-02 11:41:38'
                    createdById: 402881e522cf4f9b0122cf5d82860002
                    updatedDate: '2018-01-02 11:41:38'
                    updatedById: 402881e522cf4f9b0122cf5d82860002
                success: true
  x-code-samples:
    - lang: Curl
      source:
        $ref: >-
          ../code_samples/Curl/v1_invoices_{invoiceId}_application-parts/getundefined
    - lang: PHP
      source:
        $ref: >-
          ../code_samples/PHP/v1_invoices_{invoiceId}_application-parts/getundefined
    - lang: Java
      source:
        $ref: >-
          ../code_samples/Java/v1_invoices_{invoiceId}_application-parts/getundefined
    - lang: Python
      source:
        $ref: >-
          ../code_samples/Python/v1_invoices_{invoiceId}_application-parts/getundefined
    - lang: Ruby
      source:
        $ref: >-
          ../code_samples/Ruby/v1_invoices_{invoiceId}_application-parts/getundefined
