get:
  tags:
    - Settings
  summary: List all settings
  description: >
    Get a list of all available settings in your tenant. 


    The response message is by default in JSON format. If you want to receive
    all the available settings in csv format, include `Accept` in the header
    parameters and set it to `application/csv`.
                
    See a [200 response sample in JSON
    format](https://assets.zuora.com/zuora-documentation/ListAllSettingsResponseSample.json)
    that lists all available settings. 


    See a [200 response sample in CSV
    format](https://assets.zuora.com/zuora-documentation/ListAllSettingsResponseSample.csv)
    that lists all available settings.


    You can find a specific operation of an available setting item in your
    tenant from the 200 response body of this call. See the following common use
    cases of Settings API for how to operate on a specifc setting item.

     * Billing Rules:
       * [Get a specific setting - Billing Rules](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/AA_Get_a_specific_setting_-_Billing_Rules)
       * [Update a specific setting - Billing Rules](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/AB_Update_a_specific_setting_-_Billing_Rules)
     * Age Buckets:
       * [Get Age Buckets](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Get_Age_Buckets)
       * [Update Age Buckets](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Update_Age_Buckets)
     * Invoice Templates:
       * [Get a specific Invoice Template](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Get_a_specific_Invoice_Template)
       * [Get all Invoice Templates](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Get_all_Invoice_Templates)
       * [Create a new Invoice Template](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Create_a_new_Invoice_Template)
       * [Update a specific Invoice Template](https://knowledgecenter.zuora.com/Central_Platform/API/BB_C_Settings_API/Update_a_specific_Invoice_Template)
       * [Delete a specific Invoice Template](https://knowledgecenter.zuora.com/Central_Platform/API/BB_C_Settings_API/Delete_a_specific_Invoice_Template)
     * Communications Profiles:
       * [Get all Communication Profiles](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Get_all_Communication_Profiles)
       * [Create a new Communication Profile](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Create_a_new_Communication_Profile)
       * [Modify a Communication Profile](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Modify_a_Communication_Profile)
       * [Get all Notifications under a particular Communication Profile](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Get_all_Notifications_under_a_particular_Communication_Profile)
     * Chart of Accounts:
       * [Get Chart of Accounts](https://knowledgecenter.zuora.com/DC_Developers/BB_C_Settings_API/Settings_API_tutorials/Get_Chart_of_Accounts)
       * [Add a new Chart of Account](https://knowledgecenter.zuora.com/Central_Platform/API/BB_C_Settings_API/Settings_API_tutorials/Add_a_new_Chart_of_Account)
     * Quote Templates:
       * [Get all Quote Templates](https://knowledgecenter.zuora.com/Central_Platform/API/BB_C_Settings_API/Settings_API_tutorials/Get_all_Quote_Templates)
       * [Get a specific Quote Template](https://knowledgecenter.zuora.com/Central_Platform/API/BB_C_Settings_API/Settings_API_tutorials/Get_a_specific_Quote_Template)
       * [Create a new Quote Template](https://knowledgecenter.zuora.com/Central_Platform/API/BB_C_Settings_API/Settings_API_tutorials/Create_a_new_Quote_Template)
     * Custom Fields:
       * [View all custom fields](https://knowledgecenter.zuora.com/Central_Platform/API/BB_C_Settings_API/Settings_API_tutorials/View_all_custom_fields)
       * [View custom fields of a specific object](https://knowledgecenter.zuora.com/Central_Platform/API/BB_C_Settings_API/Settings_API_tutorials/View_custom_fields_of_a_specific_object)
       * [Update custom fields of a specific object](https://knowledgecenter.zuora.com/Central_Platform/API/BB_C_Settings_API/Settings_API_tutorials/Update_custom_fields_of_a_specific_object)
  operationId: GET_ListAllSettings
  parameters:
    - $ref: ../components/parameters/GLOBAL_HEADER_Authorization_OAuth.yaml
    - $ref: ../components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single.yaml
    - $ref: ../components/parameters/GLOBAL_HEADER_Zuora_Track_Id.yaml
    - name: Accept
      in: header
      required: false
      description: >
        Specifies response media type. If you omit the `Accept` header
        parameter, the response body is by default in JSON format. If you
        include `Accept` header parameter and set it to `application/csv`, the
        response body is in csv format.
      schema:
        type: string
        maxLength: 64
  responses:
    '200':
      description: OK
      headers:
        RateLimit-Limit:
          description: >
            The request limit quota for the time window closest to exhaustion.
            See [rate
            limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
            for more information.
          schema:
            type: string
        RateLimit-Remaining:
          description: >
            The number of requests remaining in the time window closest to quota
            exhaustion. See [rate
            limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
            for more information.
          schema:
            type: number
        RateLimit-Reset:
          description: >
            The number of seconds until the quota resets for the time window
            closest to quota exhaustion. See [rate
            limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
            for more information.
          schema:
            type: number
        Zuora-Request-Id:
          description: >
            The Zuora internal identifier of the API call. You cannot control
            the value of this header.
          schema:
            type: string
            minLength: 36
            maxLength: 36
        Zuora-Track-Id:
          description: >
            A custom identifier for tracing the API call. If you specified a
            tracing identifier in the request headers, Zuora returns the same
            tracing identifier. Otherwise, Zuora does not set this header.
          schema:
            type: string
            maxLength: 64
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ListAllSettingsResponse.yaml
          examples:
            response:
              value:
                settings:
                  - key: AccountingRules
                    description: Accounting Rules settings
                    context: Entity
                    pathPattern: /accounting-rules
                    httpOperations:
                      - method: GET
                        url: /settings/accounting-rules
                        parameters: []
                        responseType: {}
                      - method: PUT
                        url: /settings/accounting-rules
                        parameters: []
                        requestType: {}
                        responseType: {}
        application/csv:
          schema:
            $ref: ../components/schemas/ListAllSettingsResponse.yaml
  x-code-samples:
    - lang: Curl
      source:
        $ref: ../code_samples/Curl/settings_listing/getundefined
    - lang: PHP
      source:
        $ref: ../code_samples/PHP/settings_listing/getundefined
    - lang: Java
      source:
        $ref: ../code_samples/Java/settings_listing/getundefined
    - lang: Python
      source:
        $ref: ../code_samples/Python/settings_listing/getundefined
    - lang: Ruby
      source:
        $ref: ../code_samples/Ruby/settings_listing/getundefined
