get:
  summary: Retrieve a revenue automation start date
  operationId: GET_RevenueAutomationStartDate
  description: >
    Describes how to get the revenue automation start date. Request and response
    field descriptions and sample code are provided.
  tags:
    - Revenue Rules
  parameters:
    - $ref: ../components/parameters/GLOBAL_HEADER_Zuora_Track_Id.yaml
    - $ref: ../components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single.yaml
  responses:
    '200':
      headers:
        RateLimit-Limit:
          description: >
            The request limit quota for the time window closest to exhaustion.
            See [rate
            limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
            for more information.
          schema:
            type: string
        RateLimit-Remaining:
          description: >
            The number of requests remaining in the time window closest to quota
            exhaustion. See [rate
            limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
            for more information.
          schema:
            type: number
        RateLimit-Reset:
          description: >
            The number of seconds until the quota resets for the time window
            closest to quota exhaustion. See [rate
            limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
            for more information.
          schema:
            type: number
        Zuora-Request-Id:
          description: >
            The Zuora internal identifier of the API call. You cannot control
            the value of this header.
          schema:
            type: string
            minLength: 36
            maxLength: 36
        Zuora-Track-Id:
          description: >
            A custom identifier for tracing the API call. If you specified a
            tracing identifier in the request headers, Zuora returns the same
            tracing identifier. Otherwise, Zuora does not set this header.
          schema:
            type: string
            maxLength: 64
      description: ''
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ../components/schemas/GETRevenueStartDateSettingType.yaml
        application/json:
          examples:
            response:
              value:
                startDate: '2012-02-01'
                updatedOn: '2013-09-11 22:49:18'
                updatedBy: MyCorpAdmin
                success: true
  x-code-samples:
    - lang: Curl
      source:
        $ref: >-
          ../code_samples/Curl/v1_settings_finance_revenue-automation-start-date/getundefined
    - lang: PHP
      source:
        $ref: >-
          ../code_samples/PHP/v1_settings_finance_revenue-automation-start-date/getundefined
    - lang: Java
      source:
        $ref: >-
          ../code_samples/Java/v1_settings_finance_revenue-automation-start-date/getundefined
    - lang: Python
      source:
        $ref: >-
          ../code_samples/Python/v1_settings_finance_revenue-automation-start-date/getundefined
    - lang: Ruby
      source:
        $ref: >-
          ../code_samples/Ruby/v1_settings_finance_revenue-automation-start-date/getundefined
