properties:
  appliedAmount:
    description: |
      The amount that is applied to the invoice.
    format: double
    type: number
  createdById:
    description: |
      The ID of the Zuora user who created the payment or credit memo.
    format: uuid
    type: string
  createdDate:
    description: >
      The date and time when the payment or credit memo was created, in
      `yyyy-mm-dd hh:mm:ss` format. For example, 2017-12-01 15:31:10.
    format: date-time
    type: string
  creditMemoId:
    description: |
      The ID of credit memo that is applied to the specified invoice.
    format: uuid
    type: string
  paymentId:
    description: |
      The ID of the payment that is applied to the specified invoice.
    format: uuid
    type: string
  updatedById:
    description: |
      The ID of the Zuora user who last updated the payment or credit memo.
    format: uuid
    type: string
  updatedDate:
    description: >
      The date and time when the payment or credit memo was last updated, in
      `yyyy-mm-dd hh:mm:ss` format. For example, 2018-01-02 11:42:16.
    format: date-time
    type: string
title: applicationParts
type: object
