properties:
  amount:
    description: |
      The amount that is applied from the payment to the invoice.
    format: double
    type: number
  invoiceId:
    description: |
      The unique ID of the invoice that the payment is applied to.
    type: string
  invoiceNumber:
    description: >
      The number of the invoice that the payment is applied to. For example,
      `INV00000001`. 


      **Note:** When both the `invoiceNumber` and `invoiceId` fields are
      specified, the two fields must match with each other.
    type: string
  items:
    description: >
      Container for invoice items. The maximum number of items is 1,000.


      **Note:** This field is only available if you have the [Invoice Item
      Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement/C_Invoice_Item_Settlement)
      feature enabled. Invoice Item Settlement must be used together with other
      Invoice Settlement features (Unapplied Payments, and Credit and Debit
      memos).  If you wish to enable Invoice Settlement, see [Invoice Settlement
      Enablement and Checklist
      Guide](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement/Invoice_Settlement_Migration_Checklist_and_Guide)
      for more information.
    items:
      $ref: ./PaymentInvoiceApplicationItemApplyRequestType.yaml
    type: array
required:
  - amount
title: invoices
type: object
