additionalProperties:
  description: >
    Custom fields of the Product Rate Plan object. The name of each custom field
    has the form <code>*customField*__c</code>. Custom field names are case
    sensitive. See [Manage Custom
    Fields](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Manage_Custom_Fields)
    for more information.
description: |
  Container for custom fields of a Product Rate Plan object.
title: productRatePlanFieldsCustom
type: object
